import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Technical test Libheros',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className="h-full bg-white">
      <body className={`h-full`}>{children}</body>
    </html>
  );
}
